- name: install nginx
  hosts: web
  tasks:
  - name: install nginx
    ansible.builtin.debian:
      name: nginx
      state: present
    when: ansible_facts['os_family'] == 'RedHat'
  - name: install nginx
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_facts['os_family'] == 'Debian'